# Generated by Django 3.2.7 on 2021-10-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='description',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='title',
        ),
    ]
