# Generated by Django 3.2.7 on 2021-10-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211006_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='displayname',
            new_name='gamer_tag',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
