# Generated by Django 3.2.7 on 2021-10-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_myuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='picture',
            field=models.ImageField(default='images/download.png', upload_to='images/'),
        ),
    ]
