# Generated by Django 3.2.7 on 2021-10-06 00:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('rating', models.CharField(choices=[('poor', 'poor'), ('good', 'good'), ('great', 'great'), ('exceptional', 'exceptional')], max_length=150)),
                ('platform', models.CharField(choices=[('xbox', 'xbox'), ('playstation', 'playstation'), ('pc', 'pc'), ('switch', 'switch')], max_length=150)),
                ('released', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
