# Generated by Django 3.2.7 on 2021-10-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='released_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
